version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"

  app:
    build: .
    depends_on:
      - db
